# Generated by Django 3.0.6 on 2020-05-13 20:12

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('province_state', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('home_church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speakers', to='churches.Church')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
