# Generated by Django 3.0.6 on 2020-05-13 20:12

from django.db import migrations, models
import django.db.models.deletion
import sermons.models
import sermons.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sermon_type', models.CharField(choices=[('message', 'Message'), ('opening', 'Opening')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('audio_low', models.FileField(blank=True, null=True, upload_to=sermons.models.low_audio_path, validators=[sermons.validators.validate_file_extension])),
                ('audio_med', models.FileField(blank=True, null=True, upload_to=sermons.models.med_audio_path, validators=[sermons.validators.validate_file_extension])),
                ('audio_high', models.FileField(blank=True, null=True, upload_to=sermons.models.high_audio_path, validators=[sermons.validators.validate_file_extension])),
                ('video_url', models.URLField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sermons', to='schedules.Event')),
                ('speakers', models.ManyToManyField(related_name='sermons', to='speakers.Speaker')),
            ],
            options={
                'ordering': ('event', 'title'),
                'unique_together': {('event', 'title')},
            },
        ),
    ]
