# Generated by Django 4.2.11 on 2024-04-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0002_sermon_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sermon",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
