# Generated by Django 4.2.11 on 2024-05-18 16:43

from django.db import migrations, models
import sermons.models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0003_alter_sermon_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="og_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=sermons.models.og_image_path
            ),
        ),
    ]
