# Generated by Django 3.0.6 on 2020-05-13 20:12

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('province_state', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('mixlr_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ('country', 'name'),
            },
        ),
    ]
