# Generated by Django 4.2.7 on 2023-12-08 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("churches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Choir",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="choirs")),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="choirs",
                        to="churches.church",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "unique_together": {("name", "church")},
            },
        ),
    ]
