# Generated by Django 4.2.7 on 2023-12-06 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schedules", "0004_eventtemplate"),
        ("churches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Choir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="choirs")),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="choirs",
                        to="churches.church",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "unique_together": {("name", "church")},
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "choir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="songs",
                        to="songs.choir",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="songs",
                        to="schedules.event",
                    ),
                ),
            ],
        ),
    ]
