# Generated by Django 3.0.6 on 2020-05-13 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('live_mixlr_audio', models.BooleanField(default=False)),
                ('live', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streams', to='schedules.Event')),
                ('speakers', models.ManyToManyField(related_name='streams', to='speakers.Speaker')),
            ],
            options={
                'ordering': ('event', 'title'),
                'unique_together': {('event', 'title')},
            },
        ),
    ]
