# Generated by Django 3.0.8 on 2020-07-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='audio_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='video_views',
            field=models.IntegerField(default=0),
        ),
    ]
