# Generated by Django 3.0.6 on 2020-05-13 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('map_search_query', models.CharField(blank=True, max_length=300, null=True)),
                ('in_person', models.BooleanField(default=True)),
                ('live_stream', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('members', 'Members Only')], max_length=50)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='churches.Church')),
            ],
            options={
                'ordering': ('start', 'church'),
            },
        ),
    ]
