# Generated by Django 3.0.7 on 2020-06-14 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20200612_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
